import ai from "../assets/quetionpaper/May_Jun_2022-ai.pdf"
import ai2 from "../assets/quetionpaper/May_Jun_2022-ai.pdf"
import ai3 from "../assets/quetionpaper/May_Jun_2024-ai.pdf"
import cc1 from "../assets/quetionpaper/Nov_Dec_2022-cc.pdf"
import cc2 from "../assets/quetionpaper/May_Jun_2023-cc.pdf"
import cc3 from "../assets/quetionpaper/March_2024-cc.pdf"
import ts1 from "../assets/quetionpaper/May_Jun_2022-ts.pdf"
import ts2 from "../assets/quetionpaper/May_Jun_2023-ts.pdf"
import ts3 from "../assets/quetionpaper/May_Jun_2024-ts.pdf"
import ww1 from "../assets/quetionpaper/May_Jun_2022-ww.pdf"
import ww2 from "../assets/quetionpaper/May_Jun_2023-ww.pdf"
import ww3 from "../assets/quetionpaper/May_Jun_2024-ww.pdf"


const materialdata = [
  {
    id: 1,
    title: "Artificial Intelligence Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 3",
    subject: "Data Structures",
    year: "2022",
    examType: "End Sem",
    downloads: 210,
    size: "1.1 MB",
    fileUrl:ai,
  },
  {
    id: 2,
    title: "Artificial Intelligence Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 4",
    subject: "Data Structures",
    year: "2023",
    examType: "End Sem",
    downloads: 190,
    size: "1.0 MB",
    fileUrl:ai2,
  },
  {
    id: 3,
    title: "Artificial Intelligence Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 3",
    subject: "Data Structures",
    year: "2024",
    examType: "End Sem",
    downloads: 260,
    size: "1.2 MB",
    fileUrl:ai3,
  },
  {
    id: 4,
    title: "Cloud  Computing Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 4",
    subject: "Data Structures",
    year: "2023",
    examType: "End Sem",
    downloads: 240,
    size: "1.1 MB",
    fileUrl: cc1,
  },
  {
    id: 5,
    title: "Cloud  Computing Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 3",
    subject: "Data Structures",
    year: "2024",
    examType: "End Sem",
    downloads: 310,
    size: "1.3 MB",
    fileUrl: cc2,
  },
  {
    id: 6,
    title: "Cloud  Computing Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 4",
    subject: "Data Structures",
    year: "2024",
    examType: "End Sem",
    downloads: 290,
    size: "1.2 MB",
    fileUrl: cc3,
  },
  {
    id: 7,
    title: "Data Structures Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 3",
    subject: "Data Structures",
    year: "2025",
    examType: "End Sem",
    downloads: 350,
    size: "1.4 MB",
    fileUrl: "/files/cs-ds-sem3-2025.pdf",
  },
  {
    id: 8,
    title: "Data Structures Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CS",
    semester: "Sem 4",
    subject: "Data Structures",
    year: "2025",
    examType: "End Sem",
    downloads: 330,
    size: "1.3 MB",
    fileUrl: "/files/cs-ds-sem4-2025.pdf",
  },

  // ================= ECE =================
  {
    id: 9,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2022",
    examType: "End Sem",
    downloads: 200,
    size: "950 KB",
    fileUrl: "/files/ece-de-sem3-2022.pdf",
  },
  {
    id: 10,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Digital Electronics",
    year: "2022",
    examType: "End Sem",
    downloads: 180,
    size: "980 KB",
    fileUrl: "/files/ece-de-sem4-2022.pdf",
  },
  {
    id: 11,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2023",
    examType: "End Sem",
    downloads: 240,
    size: "1.0 MB",
    fileUrl: "/files/ece-de-sem3-2023.pdf",
  },
  {
    id: 12,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Digital Electronics",
    year: "2023",
    examType: "End Sem",
    downloads: 220,
    size: "1.0 MB",
    fileUrl: "/files/ece-de-sem4-2023.pdf",
  },
  {
    id: 13,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2024",
    examType: "End Sem",
    downloads: 280,
    size: "1.1 MB",
    fileUrl: "/files/ece-de-sem3-2024.pdf",
  },
  {
    id: 14,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Digital Electronics",
    year: "2024",
    examType: "End Sem",
    downloads: 260,
    size: "1.1 MB",
    fileUrl: "/files/ece-de-sem4-2024.pdf",
  },
  {
    id: 15,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2025",
    examType: "End Sem",
    downloads: 320,
    size: "1.2 MB",
    fileUrl: "/files/ece-de-sem3-2025.pdf",
  },
  {
    id: 16,
    title: "Digital Electronics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Digital Electronics",
    year: "2025",
    examType: "End Sem",
    downloads: 300,
    size: "1.2 MB",
    fileUrl: "/files/ece-de-sem4-2025.pdf",
  },

  // ================= ME =================
  {
    id: 17,
    title: "Design of transmission System Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ME",
    semester: "Sem 3",
    subject: "Thermodynamics",
    year: "2022",
    examType: "End Sem",
    downloads: 160,
    size: "1.2 MB",
    fileUrl: ts1,
  },
  {
    id: 18,
    title: "Design of transmission System Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ME",
    semester: "Sem 4",
    subject: "Thermodynamics",
    year: "2022",
    examType: "End Sem",
    downloads: 150,
    size: "1.1 MB",
    fileUrl: ts2,
  },
  {
    id: 19,
    title: "Design of transmission System Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ME",
    semester: "Sem 3",
    subject: "Thermodynamics",
    year: "2023",
    examType: "End Sem",
    downloads: 180,
    size: "1.3 MB",
    fileUrl: ts3,
  },
  {
    id: 20,
    title: "Thermodynamics Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ME",
    semester: "Sem 4",
    subject: "Thermodynamics",
    year: "2023",
    examType: "End Sem",
    downloads: 170,
    size: "1.2 MB",
    fileUrl: "/files/me-thermo-sem4-2023.pdf",
  },

  // ================= CIVIL =================
  {
    id: 21,
    title: "Waste Water Engineering Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "CIVIL",
    semester: "Sem 3",
    subject: "Engineering Mechanics",
    year: "2022",
    examType: "End Sem",
    downloads: 190,
    size: "1.0 MB",
    fileUrl: ww1,
  },
  {
    id: 22,
    title: "Waste Water Engineering Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "CIVIL",
    semester: "Sem 4",
    subject: "Engineering Mechanics",
    year: "2022",
    examType: "End Sem",
    downloads: 180,
    size: "1.0 MB",
    fileUrl: ww2,
  },
    {
    id: 222,
    title: "Waste Water Engineering Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "CIVIL",
    semester: "Sem 4",
    subject: "Engineering Mechanics",
    year: "2022",
    examType: "End Sem",
    downloads: 180,
    size: "1.0 MB",
    fileUrl: ww3,
  },


  // ================= CHEMICAL =================
  {
    id: 23,
    title: "Process Calculations Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "CHEMICAL",
    semester: "Sem 3",
    subject: "Process Calculations",
    year: "2022",
    examType: "End Sem",
    downloads: 150,
    size: "1.1 MB",
    fileUrl: "/files/chem-pc-sem3-2022.pdf",
  },
  {
    id: 24,
    title: "Process Calculations Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "CHEMICAL",
    semester: "Sem 4",
    subject: "Process Calculations",
    year: "2022",
    examType: "End Sem",
    downloads: 140,
    size: "1.0 MB",
    fileUrl: "/files/chem-pc-sem4-2022.pdf",
  },
];

export default materialdata;
