import notebook from "../assets/notebook.png";


const stationarydata = [
  {
    id: 1,
    name: "Classmate Notebook",
    description: "200 pages ruled notebook ideal for engineering students",
    price: 120,
    image: notebook,
    category: "Stationery",
  },
  {
    id: 2,
    name: "Engineering Drawing Instruments Box",
    description: "Complete set including compass, divider, scale, and pencil",
    price: 350,
    image: "/images/stationery/instrument-box.jpg",
    category: "Stationery",
  },
  {
    id: 3,
    name: "Scientific Calculator",
    description: "Casio scientific calculator approved for exams",
    price: 999,
    image: "/images/stationery/calculator.jpg",
    category: "Stationery",
  },
  {
    id: 4,
    name: "A4 Drawing Sheets (Pack of 20)",
    description: "High quality sheets for engineering graphics",
    price: 180,
    image: "/images/stationery/drawing-sheets.jpg",
    category: "Stationery",
  },
  {
    id: 5,
    name: "Blue Ball Pen (Pack of 10)",
    description: "Smooth writing ball pens for daily use",
    price: 90,
    image: "/images/stationery/pen.jpg",
    category: "Stationery",
  },
  {
    id: 6,
    name: "Mechanical Pencil",
    description: "0.5mm mechanical pencil with refill",
    price: 75,
    image: "/images/stationery/mech-pencil.jpg",
    category: "Stationery",
  },
  {
    id: 7,
    name: "Highlighter Set",
    description: "Set of 5 neon color highlighters",
    price: 150,
    image: "/images/stationery/highlighter.jpg",
    category: "Stationery",
  },
  {
    id: 8,
    name: "Geometry Box",
    description: "Student geometry box with all tools",
    price: 130,
    image: "/images/stationery/geometry-box.jpg",
    category: "Stationery",
  },
  {
    id: 9,
    name: "Sticky Notes Pack",
    description: "Colorful sticky notes for reminders",
    price: 60,
    image: "/images/stationery/sticky-notes.jpg",
    category: "Stationery",
  },
  {
    id: 10,
    name: "File Folder",
    description: "Plastic file folder for documents",
    price: 50,
    image: "/images/stationery/file.jpg",
    category: "Stationery",
  },

  {
    id: 101,
    name: "Engineering Mathematics",
    description: "Covers calculus, algebra, and probability",
    price: 499,
    image: "/images/books/engineering-maths.jpg",
    category: "Textbook",
  },
  {
    id: 102,
    name: "Data Structures & Algorithms",
    description: "Essential DSA concepts with examples",
    price: 549,
    image: "/images/books/dsa.jpg",
    category: "Textbook",
  },
  {
    id: 103,
    name: "Circuit Analysis",
    description: "Fundamentals of electrical circuits",
    price: 399,
    image: "/images/books/circuit-analysis.jpg",
    category: "Textbook",
  },
  {
    id: 104,
    name: "Engineering Graphics",
    description: "Technical drawing and CAD basics",
    price: 299,
    image: "/images/books/engineering-graphics.jpg",
    category: "Textbook",
  },
  {
    id: 105,
    name: "Operating Systems",
    description: "Processes, memory, and file systems",
    price: 579,
    image: "/images/books/os.jpg",
    category: "Textbook",
  },
  {
    id: 106,
    name: "Computer Networks",
    description: "Networking concepts and protocols",
    price: 459,
    image: "/images/books/networks.jpg",
    category: "Textbook",
  },
  {
    id: 107,
    name: "Database Management Systems",
    description: "SQL, normalization, and transactions",
    price: 529,
    image: "/images/books/dbms.jpg",
    category: "Textbook",
  },
  {
    id: 108,
    name: "Digital Electronics",
    description: "Logic gates, flip-flops, and circuits",
    price: 389,
    image: "/images/books/digital-electronics.jpg",
    category: "Textbook",
  },
  {
    id: 109,
    name: "Software Engineering",
    description: "SDLC models and project management",
    price: 449,
    image: "/images/books/software-engineering.jpg",
    category: "Textbook",
  },
  {
    id: 110,
    name: "Artificial Intelligence Basics",
    description: "Introduction to AI and machine learning",
    price: 599,
    image: "/images/books/ai.jpg",
    category: "Textbook",
  },
];

export default stationarydata;
