import notebook from "../assets/notebook.png";

const stationarydata = [
  {
    id: 1,
    name: "Classmate Notebook",
    description: "200 pages ruled notebook ideal for engineering students",
    price: 120,
    discount: 10,            // ✅ 10% discount
    image: notebook,
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 2,
    name: "Engineering Drawing Instruments Box",
    description: "Complete set including compass, divider, scale, and pencil",
    price: 350,
    discount: 5,
    image: "/images/stationery/instrument-box.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 3,
    name: "Scientific Calculator",
    description: "Casio scientific calculator approved for exams",
    price: 999,
    discount: 15,
    image: "/images/stationery/calculator.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 4,
    name: "A4 Drawing Sheets (Pack of 20)",
    description: "High quality sheets for engineering graphics",
    price: 180,
    discount: 8,
    image: "/images/stationery/drawing-sheets.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 5,
    name: "Blue Ball Pen (Pack of 10)",
    description: "Smooth writing ball pens for daily use",
    price: 90,
    discount: 0,            // ✅ no discount
    image: "/images/stationery/pen.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 6,
    name: "Mechanical Pencil",
    description: "0.5mm mechanical pencil with refill",
    price: 75,
    discount: 5,
    image: "/images/stationery/mech-pencil.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 7,
    name: "Highlighter Set",
    description: "Set of 5 neon color highlighters",
    price: 150,
    discount: 10,
    image: "/images/stationery/highlighter.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 8,
    name: "Geometry Box",
    description: "Student geometry box with all tools",
    price: 130,
    discount: 5,
    image: "/images/stationery/geometry-box.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 9,
    name: "Sticky Notes Pack",
    description: "Colorful sticky notes for reminders",
    price: 60,
    discount: 0,
    image: "/images/stationery/sticky-notes.jpg",
    category: "Stationery",
    quantity: 1,
  },
  {
    id: 10,
    name: "File Folder",
    description: "Plastic file folder for documents",
    price: 50,
    discount: 0,
    image: "/images/stationery/file.jpg",
    category: "Stationery",
    quantity: 1,
  },

  // 📚 TEXTBOOKS
  {
    id: 101,
    name: "Engineering Mathematics",
    description: "Covers calculus, algebra, and probability",
    price: 499,
    discount: 20,
    image: "/images/books/engineering-maths.jpg",
    category: "Textbook",
    quantity: 1,
  },
  {
    id: 102,
    name: "Data Structures & Algorithms",
    description: "Essential DSA concepts with examples",
    price: 549,
    discount: 15,
    image: "/images/books/dsa.jpg",
    category: "Textbook",
    quantity: 1,
  },
  {
    id: 103,
    name: "Circuit Analysis",
    description: "Fundamentals of electrical circuits",
    price: 399,
    discount: 10,
    image: "/images/books/circuit-analysis.jpg",
    category: "Textbook",
    quantity: 1,
  },
  {
    id: 104,
    name: "Engineering Graphics",
    description: "Technical drawing and CAD basics",
    price: 299,
    discount: 5,
    image: "/images/books/engineering-graphics.jpg",
    category: "Textbook",
    quantity: 1,
  },
  {
    id: 105,
    name: "Operating Systems",
    description: "Processes, memory, and file systems",
    price: 579,
    discount: 18,
    image: "/images/books/os.jpg",
    category: "Textbook",
    quantity: 1,
  },
];

export default stationarydata;
