import ai from "../assets/quetionpaper/Oct 2025.pdf"
import ai2 from "../assets/quetionpaper/August_2025.pdf"
import ai3 from "../assets/quetionpaper/Nov_Dec_2025.pdf"
import cc1 from "../assets/quetionpaper/Nov_Dec_2025 (1).pdf"
import cc2 from "../assets/quetionpaper/August_2025 (1).pdf"
import cc3 from "../assets/quetionpaper/Nov_Dec_2025 (2).pdf"
import ts1 from "../assets/quetionpaper/Nov_Dec_2024.pdf"
import ts2 from "../assets/quetionpaper/May_Jun_2025.pdf"
import oop from "../assets/quetionpaper/March_2026.pdf"
import tss from "../assets/quetionpaper/May_Jun_2025 (1).pdf"

const materialdata = [
  {
    id: 1,
    title: "Computer Organization Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Computer Organization",
    year: "2022",
    examType: "End Sem",
    downloads: 210,
    size: "1.1 MB",
    fileUrl:ai,
  },
  {
    id: 2,
    title: "Advanced java Programming Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "advanced java Programming",
    year: "2023",
    examType: "End Sem",
    downloads: 190,
    size: "1.0 MB",
    fileUrl:ai2,
  },
  {
    id: 3,
    title: "Data communication Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Data communication",
    year: "2024",
    examType: "End Sem",
    downloads: 260,
    size: "1.2 MB",
    fileUrl:ai3,
  },
  {
    id: 4,
    title: "Block chain Technology Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Block chain Technology",
    year: "2023",
    examType: "End Sem",
    downloads: 240,
    size: "1.1 MB",
    fileUrl: cc1,
  },
  {
    id: 5,
    title: "Database management system Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Database management system",
    year: "2024",
    examType: "End Sem",
    downloads: 310,
    size: "1.3 MB",
    fileUrl: cc2,
  },
  {
    id: 6,
    title: "Microcontroller and Applications Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Microcontroller and Applications",
    year: "2024",
    examType: "End Sem",
    downloads: 290,
    size: "1.2 MB",
    fileUrl: cc3,
  },
  {
    id: 7,
    title: "Data Structures Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Data Structures",
    year: "2025",
    examType: "End Sem",
    downloads: 350,
    size: "1.4 MB",
    fileUrl: ts1,
  },
  {
    id: 8,
    title: "System Programming And Operating System",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "System Programming And Operating System",
    year: "2025",
    examType: "End Sem",
    downloads: 330,
    size: "1.3 MB",
    fileUrl: tss,
  },

  // ================= ECE =================
  {
    id: 9,
    title: "Electronic Circuits Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2022",
    examType: "End Sem",
    downloads: 200,
    size: "950 KB",
    fileUrl: ts2,
  },
  {
    id: 10,
    title: "Object Oriented Programming Question Paper",
    description: "University Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 4",
    subject: "Object Oriented Programming",
    year: "2022",
    examType: "End Sem",
    downloads: 180,
    size: "980 KB",
    fileUrl: oop,
  }
];

export default materialdata;


